name: clepsydra
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  vibration: ^3.1.5
  http: ^1.6.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/clepsydra.png
    - assets/lottie/hourglass.json
    - assets/lottie/glass.json

flutter_native_splash:
  color: "#180C26"
  background_image: "assets/images/clepsydra.png"
  android_12:
    color: "#180C26"
    background_image: "assets/images/clepsydra.png"
